# Generated by Django 5.2.4 on 2025-08-03 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_problem_codesubmission_error_codesubmission_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='compiler.problem'),
        ),
    ]
